<a href="https://colab.research.google.com/github/Martinslica/DESAFIO_CAGED/blob/master/Desafio2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Desafio 2

## Instruções básicas

O desafio 2 é sobre a extração, limpeza e manipulação de dados no INEP sobre o Censo da Educação Superior. Estão apresentados abaixo um artigo de 2016 sobre a divulgação dos dados, assim como um vídeo sobre esta masma divulgação, da edição de 2015. Além disso, está oferecido o Manual de Instruções da última edição publicada, de 2017.

Ao final, são colocadas as questões do desafio em duas partes, a primeira coletiva para ser feita em grupo, e a segunda para ser feita individual. Qualquer dúvida ou comentário, por favor procure o corpo docente.

# MEC e Inep divulgam dados do Censo da Educação Superior 2016

<br>
<img src="img/inep.png" width="550" />
<br>


Em 2016, 34.366 cursos de graduação foram ofertados em 2.407 instituições de educação superior (IES) no Brasil para um total de 8.052.254 estudantes matriculados. Os dados são do Censo da Educação Superior e foram divulgados nesta quinta feira (31) em coletiva de imprensa com a presença do ministro da Educação, Mendonça Filho, da secretária executiva do Ministério da Educação (Mec), Maria Helena Guimarães de Castro, e da presidente do Instituto Nacional de Estudos e Estatísticas Educacionais Anísio Teixeira (Inep), Maria Inês Fini.

Segundo as estatísticas apresentadas, as 197 universidades existentes no país equivalem a 8,2% do total de IES, mas concentram 53,7% das matrículas em cursos de graduação.

No ano passado, o número de matrículas na educação superior (graduação e sequencial) continuou crescendo, mas essa tendência desacelerou quando se comparado aos últimos anos. Entre 2006 e 2016, houve aumento de 62,8%, com uma média anual de 5% de crescimento. Porém, em relação a 2015, a variação positiva foi de apenas 0,2%.

## Cursos

Os cursos de bacharelado mantêm sua predominância na educação superior brasileira com uma participação de 69% das matrículas. Os cursos de licenciatura tiveram o maior crescimento (3,3%) entre os graus acadêmicos em 2016, quando comparado a 2015.

## Vagas

Em 2016, foram oferecidas mais de 10,6 milhões de vagas em cursos de graduação, sendo 73,8% vagas novas e 26,0%, vagas remanescentes. Das novas vagas oferecidas no ano passado, 33,5% foram preenchidas, enquanto apenas 12,0% das vagas remanescentes foram ocupadas no mesmo período.

## Ingressantes

Em 2016, quase 3 milhões de alunos ingressaram em cursos de educação superior de graduação. Desse total, 82,3% em instituições privadas.
Após uma queda observada em 2015, o número de ingressantes teve um crescimento de 2,2% em 2016. Isso ocorreu porque a modalidade a distância aumentou mais de 20% entre os dois anos, enquanto nos cursos presenciais houve um decréscimo no número de ingressantes de 3,7%.

## Concluintes

No ano passado, mais de um 1,1 milhão de estudantes concluíram a educação superior. O número de concluintes em cursos de graduação presencial teve aumento de 2,4% em relação a 2015. A modalidade a distância diminuiu -1,3% no mesmo período.

Entre 2015 e 2016, o número de concluintes na rede pública aumentou 2,9%. Já na rede privada a variação positiva foi de 1,4%. No período de 2006 a 2016, a variação percentual do número de concluintes em cursos de graduação foi maior na rede privada, com 62,6%, enquanto na pública esse crescimento foi de 26,5% no mesmo período.

## Censo da Educação Superior

O Censo da Educação Superior, realizado anualmente pelo Instituto Nacional de Estudos e Pesquisas Educacionais Anísio Teixeira (Inep), constitui-se importante instrumento de obtenção de dados para a geração de informações que subsidiam a formulação, o monitoramento e a avaliação das políticas públicas, além de ser elemento importante para elaboração de estudos e pesquisas sobre o setor. O Censo coleta informações sobre as Instituições de Educação Superior (IES), os cursos de graduação e sequenciais de formação específica e sobre os discentes e docentes vinculados a esses cursos.

Os resultados coletados subsidiam o Sistema Nacional de Avaliação da Educação Superior (Sinaes), seja no cálculo dos indicadores de Conceito Preliminar de Curso (CPC) e do Índice Geral de Cursos (IGC), seja no fornecimento de informações, como número de matrículas, de ingressos, de concluintes, entre outras. As estatísticas possibilitam ainda, através da justaposição de informações de diferentes edições da pesquisa, a análise da trajetória dos estudantes a partir de seu ingresso em determinado curso de graduação, e, consequentemente, a geração de indicadores de acompanhamento e de fluxo na educação superior.

In [0]:
# Vídeo sobre a divulgação dos resultados do Censo da Educação Superior da edição de 2015

from IPython.display import HTML


HTML('<iframe width="640" height="360" src="https://www.youtube.com/embed/31rWZN5D_YE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>')

C:\Users\marco\Anaconda3\lib\site-packages\IPython\core\display.py:689: UserWarning: Consider using IPython.display.IFrame instead
  warnings.warn("Consider using IPython.display.IFrame instead")

# Microdados do Censo da Educação Superior 2017 

## Manual do Usuário 

### Ministério da Educação Instituto Nacional de Estudos e Pesquisas Educacionais Anísio Teixeira – INEP Diretoria de Estatísticas Educacionais 

O Instituto Nacional de Estudos e Pesquisas Educacionais Anísio Teixeira (Inep), autarquia vinculada ao Ministério da Educação, tem como missão institucional produzir e disseminar informações educacionais. As estatísticas e avaliações produzidas pelo Inep visam fornecer os subsídios para a formulação e implementação de políticas voltadas para a melhoria contínua da educação no país. 

Entre as informações educacionais produzidas pelo Inep, destacam-se os dados coletados no Censo da Educação Superior, levantamento de âmbito nacional, realizado anualmente pela Diretoria de Estatísticas Educacionais em todas as Instituições de Educação Superior (IES), públicas e privadas do país. 

O Inep desenvolve uma série de ações de disseminação de dados que se encontram divulgados de forma ativa no portal do instituto na internet (www.inep.gov.br ). O presente documento figura entre os instrumentos utilizados por este Instituto para garantir a transparência requerida pela sociedade e promover a participação dos diferentes agentes sociais envolvidos nas ações educativas. 

Nesse contexto, os Microdados foram estruturados em formato CSV (CommaSeparated Values) e seus dados estão delimitados por Pipe ( | ), de modo a garantir que praticamente qualquer software estatístico, inclusive open source, consiga importar e carregar as bases de dados. 

Por meio dos Microdados é possível obter um amplo panorama da educação brasileira e, como importante ferramenta de transparência, é indubitavelmente um rico acervo sobre a educação superior do nosso país e uma fonte segura e eficaz de obtenção de dados, acessíveis aos pesquisadores, estudantes, gestores e sociedade em geral. 

#### DADOS 

Estão disponíveis no site do Inep os Microdados do Censo da Educação Superior 2017 (DM_IES, DM_CURSO, DM_DOCENTE, DM_ALUNO, DM_LOCAL_OFERTA e TB_AUX_AREA_OCDE) em formato CSV delimitados por Pipe ( | ). Os arquivos encontram-se compactados (em formato .zip) pelo software 7-zip e devem ser descompactados no diretório C:\ do seu disco rígido.  
 
#### LEIA-ME 

Este presente instrumento traz instruções fundamentais para a correta extração e manipulação dos Microdados, como orientações para abrir os arquivos nos softwares R, SPSS e SAS. É, portanto, uma espécie de “Manual do Usuário” que traz os Dicionários das Variáveis do Censo da Educação Superior 2017. 
 
#### FILTROS DA EDUCAÇÃO SUPERIOR 

É um documento que norteia o usuário na obtenção de dados em sintonia com os valores publicados nas Sinopses Estatísticas produzidas pelo INEP. Nele, são elencados, de forma simples, os principais filtros e funções que devem ser aplicados. 
 
#### ANEXO I – Dicionários de dados e Tabelas Auxiliares 

Contém, em formato .xlsx (Excel), o Dicionário de Dados do Censo da Educação Superior 2017 e também uma tabela auxiliar com o código e o nome dos países: 

1.DICIONÁRIO DE DADOS 

- TABELA DE ALUNO 
- TABELA DE CURSO 
- TABELA DE IES 
- TABELA DE LOCAL DE OFERTA 
- TABELA DE DOCENTE 
- TABELA AUXILIAR OCDE 
 
2.TABELA CONTENDO O NOME DO PAÍS DE ORIGEM OU NATURALIZAÇÃO 
 
#### ANEXO II – Questionários do Censo da Educação Superior  

Contém, em formato .pdf (Portable Document Format), os seguintes questionários do Censo da Educação Superior 2017 e estão disponíveis para download na pasta anexos: 

- MÓDULO IES 
- MÓDULO CURSO 
- MÓDULO DOCENTE 
- MÓDULO ALUNO

# DESAFIO 2

<br>
<img src="img/dh.png" width="550" />
<br>

## Parte Coletiva

### Obrigatório:

1) Tabelas com número de universidades públicas e privadas por estado e número de alunos por universidade 

2) Pergunta-se: é verdade que existe menos mulheres nos cursos de exatas? Explique com os dados.

3) Quantos cursos novos abrem por ano? 

4) Se usarmos a taxa de concluientes de um curso como variável de dificuldade dos cursos, eles tem ficado mais faceis ou mais duros ao longo do tempo? Quais as dificuldades para uma afirmação dessas?

5) Rode uma regressão multipla que explique o abandono dos cursos, será que professores mais/menos preparados influência nessas taxas?

6) Quais os cursos com maior crescimento de matriculas por região? E quais os com maior queda? Como você explicaria isso.

7) Construa uma variável "Signo" dos estudantes e explique porque ela é correlacionada com a variável "probabilidade de formação" (construir)

### Facultativo:

1) Crie um mapa das universidades no pais.

2) Alunos estrangeiros são melhores resilientes (para terminar um curso) que os brasileiros? Quais as dificuldades dessa análise?

3) Se você tivesse que abrir um curso (apenas um curso de graduação), qual seria, onde ele seria, qual a modalidade.

## Parte Individual.

### Obrigatório:

1) Pense na Hipótese de 2 universidades A e B onde X é a média de notas delas e elas tem exatamente os mesmos cursos. É possível que A_X > B_X e TODOS os cursos de B sejam melhores (notas maiores) que os de A? Explique (não são necessários códigos, apenas a explicação). Dica: paradoxo de simpson.

2) Rode uma regressão multipla que use, entre outras, a carga horária de um curso como variavel independente para explicar a idade dos alunos formados.

3) Qual a probabilidade de pegarmos um professor ao acaso no Brasil e ele ter mais do que o dobro da sua idade dado que ele é homem.

Obs: Não usar informações que não estejam na pasta Desafios nas partes **Obrigatórias**

## Data da entrega: 22 de Novembro (sexta-feira)

# DESAFIO 2 - Grupo:

Nome dos integrantes do grupo

In [0]:
# Verona
# Lilian
# Paulo
# Felipe
# Bruno
# Luciano

In [11]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [13]:
cd 'drive/My Drive/Data Science/Modulo 2/Desafio 2-20191108/DADOS/'

[Errno 2] No such file or directory: 'drive/My Drive/Data Science/Modulo 2/Desafio 2-20191108/DADOS/'
/content

In [12]:
cd 'divre/Colab Notebooks/Desafio 2'

[Errno 2] No such file or directory: 'divre/Colab Notebooks/Desafio 2'
/content

In [4]:
! ls

drive  sample_data

In [0]:
import pandas as pd
import sqlite3
import csv

In [6]:
con = sqlite3.connect(":memory:")
cur = con.cursor()
cur.execute('''
  CREATE TABLE ALUNOS (NU_ANO_CENSO,
 CO_IES,
 TP_CATEGORIA_ADMINISTRATIVA,
 TP_ORGANIZACAO_ACADEMICA,
 CO_CURSO,
 CO_CURSO_POLO,
 TP_TURNO,
 TP_GRAU_ACADEMICO,
 TP_MODALIDADE_ENSINO,
 TP_NIVEL_ACADEMICO,
 CO_OCDE_AREA_GERAL,
 CO_OCDE_AREA_ESPECIFICA,
 CO_OCDE_AREA_DETALHADA,
 CO_OCDE,
 CO_ALUNO,
 CO_ALUNO_CURSO,
 CO_ALUNO_CURSO_ORIGEM,
 TP_COR_RACA,
 TP_SEXO,
 NU_ANO_NASCIMENTO,
 NU_MES_NASCIMENTO,
 NU_DIA_NASCIMENTO,
 NU_IDADE,
 TP_NACIONALIDADE,
 CO_PAIS_ORIGEM,
 CO_UF_NASCIMENTO,
 CO_MUNICIPIO_NASCIMENTO,
 TP_DEFICIENCIA,
 IN_DEFICIENCIA_AUDITIVA,
 IN_DEFICIENCIA_FISICA,
 IN_DEFICIENCIA_INTELECTUAL,
 IN_DEFICIENCIA_MULTIPLA,
 IN_DEFICIENCIA_SURDEZ,
 IN_DEFICIENCIA_SURDOCEGUEIRA,
 IN_DEFICIENCIA_BAIXA_VISAO,
 IN_DEFICIENCIA_CEGUEIRA,
 IN_DEFICIENCIA_SUPERDOTACAO,
 IN_TGD_AUTISMO_INFANTIL,
 IN_TGD_SINDROME_ASPERGER,
 IN_TGD_SINDROME_RETT,
 IN_TGD_TRANSTOR_DESINTEGRATIVO,
 TP_SITUACAO,
 QT_CARGA_HORARIA_TOTAL,
 QT_CARGA_HORARIA_INTEG,
 DT_INGRESSO_CURSO,
 IN_INGRESSO_VESTIBULAR,
 IN_INGRESSO_ENEM,
 IN_INGRESSO_AVALIACAO_SERIADA,
 IN_INGRESSO_SELECAO_SIMPLIFICA,
 IN_INGRESSO_OUTRO_TIPO_SELECAO,
 IN_INGRESSO_VAGA_REMANESC,
 IN_INGRESSO_VAGA_PROG_ESPECIAL,
 IN_INGRESSO_TRANSF_EXOFFICIO,
 IN_INGRESSO_DECISAO_JUDICIAL,
 IN_INGRESSO_CONVENIO_PECG,
 IN_INGRESSO_EGRESSO,
 IN_INGRESSO_OUTRA_FORMA,
 IN_RESERVA_VAGAS,
 IN_RESERVA_ETNICO,
 IN_RESERVA_DEFICIENCIA,
 IN_RESERVA_ENSINO_PUBLICO,
 IN_RESERVA_RENDA_FAMILIAR,
 IN_RESERVA_OUTRA,
 IN_FINANCIAMENTO_ESTUDANTIL,
 IN_FIN_REEMB_FIES,
 IN_FIN_REEMB_ESTADUAL,
 IN_FIN_REEMB_MUNICIPAL,
 IN_FIN_REEMB_PROG_IES,
 IN_FIN_REEMB_ENT_EXTERNA,
 IN_FIN_REEMB_OUTRA,
 IN_FIN_NAOREEMB_PROUNI_INTEGR,
 IN_FIN_NAOREEMB_PROUNI_PARCIAL,
 IN_FIN_NAOREEMB_ESTADUAL,
 IN_FIN_NAOREEMB_MUNICIPAL,
 IN_FIN_NAOREEMB_PROG_IES,
 IN_FIN_NAOREEMB_ENT_EXTERNA,
 IN_FIN_NAOREEMB_OUTRA,
 IN_APOIO_SOCIAL,
 IN_APOIO_ALIMENTACAO,
 IN_APOIO_BOLSA_PERMANENCIA,
 IN_APOIO_BOLSA_TRABALHO,
 IN_APOIO_MATERIAL_DIDATICO,
 IN_APOIO_MORADIA,
 IN_APOIO_TRANSPORTE,
 IN_ATIVIDADE_EXTRACURRICULAR,
 IN_COMPLEMENTAR_ESTAGIO,
 IN_COMPLEMENTAR_EXTENSAO,
 IN_COMPLEMENTAR_MONITORIA,
 IN_COMPLEMENTAR_PESQUISA,
 IN_BOLSA_ESTAGIO,
 IN_BOLSA_EXTENSAO,
 IN_BOLSA_MONITORIA,
 IN_BOLSA_PESQUISA,
 TP_ESCOLA_CONCLUSAO_ENS_MEDIO,
 IN_ALUNO_PARFOR,
 TP_SEMESTRE_CONCLUSAO,
 TP_SEMESTRE_REFERENCIA,
 IN_MOBILIDADE_ACADEMICA,
 TP_MOBILIDADE_ACADEMICA,
 TP_MOBILIDADE_ACADEMICA_INTERN,
 CO_IES_DESTINO,
 CO_PAIS_DESTINO,
 IN_MATRICULA,
 IN_CONCLUINTE,
 IN_INGRESSO_TOTAL,
 IN_INGRESSO_VAGA_NOVA,
 IN_INGRESSO_PROCESSO_SELETIVO,
 NU_ANO_INGRESSO);''')

with open('DM_ALUNO.csv','rb') as fin:     
    dr = csv.DictReader(fin, delimiter='|')
    to_db = [(i['NU_ANO_CENSO'],
              i['CO_IES'],
              i['TP_CATEGORIA_ADMINISTRATIVA'],
              i['TP_ORGANIZACAO_ACADEMICA'],
              i['CO_CURSO'],
              i['CO_CURSO_POLO'],
              i['TP_TURNO'],
              i['TP_GRAU_ACADEMICO'],
              i['TP_MODALIDADE_ENSINO'],
              i['TP_NIVEL_ACADEMICO'],
              i['CO_OCDE_AREA_GERAL'],
              i['CO_OCDE_AREA_ESPECIFICA'],
              i['CO_OCDE_AREA_DETALHADA'],
              i['CO_OCDE'],
              i['CO_ALUNO'],
              i['CO_ALUNO_CURSO'],
              i['CO_ALUNO_CURSO_ORIGEM'],
              i['TP_COR_RACA'],
              i['TP_SEXO'],
              i['NU_ANO_NASCIMENTO'],
              i['NU_MES_NASCIMENTO'],
              i['NU_DIA_NASCIMENTO'],
              i['NU_IDADE'],
              i['TP_NACIONALIDADE'],
              i['CO_PAIS_ORIGEM'],
              i['CO_UF_NASCIMENTO'],
              i['CO_MUNICIPIO_NASCIMENTO'],
              i['TP_DEFICIENCIA'],
              i['IN_DEFICIENCIA_AUDITIVA'],
              i['IN_DEFICIENCIA_FISICA'],
              i['IN_DEFICIENCIA_INTELECTUAL'],
              i['IN_DEFICIENCIA_MULTIPLA'],
              i['IN_DEFICIENCIA_SURDEZ'],
              i['IN_DEFICIENCIA_SURDOCEGUEIRA'],
              i['IN_DEFICIENCIA_BAIXA_VISAO'],
              i['IN_DEFICIENCIA_CEGUEIRA'],
              i['IN_DEFICIENCIA_SUPERDOTACAO'],
              i['IN_TGD_AUTISMO_INFANTIL'],
              i['IN_TGD_SINDROME_ASPERGER'],
              i['IN_TGD_SINDROME_RETT'],
              i['IN_TGD_TRANSTOR_DESINTEGRATIVO'],
              i['TP_SITUACAO'],
              i['QT_CARGA_HORARIA_TOTAL'],
              i['QT_CARGA_HORARIA_INTEG'],
              i['DT_INGRESSO_CURSO'],
              i['IN_INGRESSO_VESTIBULAR'],
              i['IN_INGRESSO_ENEM'],
              i['IN_INGRESSO_AVALIACAO_SERIADA'],
              i['IN_INGRESSO_SELECAO_SIMPLIFICA'],
              i['IN_INGRESSO_OUTRO_TIPO_SELECAO'],
              i['IN_INGRESSO_VAGA_REMANESC'],
              i['IN_INGRESSO_VAGA_PROG_ESPECIAL'],
              i['IN_INGRESSO_TRANSF_EXOFFICIO'],
              i['IN_INGRESSO_DECISAO_JUDICIAL'],
              i['IN_INGRESSO_CONVENIO_PECG'],
              i['IN_INGRESSO_EGRESSO'],
              i['IN_INGRESSO_OUTRA_FORMA'],
              i['IN_RESERVA_VAGAS'],
              i['IN_RESERVA_ETNICO'],
              i['IN_RESERVA_DEFICIENCIA'],
              i['IN_RESERVA_ENSINO_PUBLICO'],
              i['IN_RESERVA_RENDA_FAMILIAR'],
              i['IN_RESERVA_OUTRA'],
              i['IN_FINANCIAMENTO_ESTUDANTIL'],
              i['IN_FIN_REEMB_FIES'],
              i['IN_FIN_REEMB_ESTADUAL'],
              i['IN_FIN_REEMB_MUNICIPAL'],
              i['IN_FIN_REEMB_PROG_IES'],
              i['IN_FIN_REEMB_ENT_EXTERNA'],
              i['IN_FIN_REEMB_OUTRA'],
              i['IN_FIN_NAOREEMB_PROUNI_INTEGR'],
              i['IN_FIN_NAOREEMB_PROUNI_PARCIAL'],
              i['IN_FIN_NAOREEMB_ESTADUAL'],
              i['IN_FIN_NAOREEMB_MUNICIPAL'],
              i['IN_FIN_NAOREEMB_PROG_IES'],
              i['IN_FIN_NAOREEMB_ENT_EXTERNA'],
              i['IN_FIN_NAOREEMB_OUTRA'],
              i['IN_APOIO_SOCIAL'],
              i['IN_APOIO_ALIMENTACAO'],
              i['IN_APOIO_BOLSA_PERMANENCIA'],
              i['IN_APOIO_BOLSA_TRABALHO'],
              i['IN_APOIO_MATERIAL_DIDATICO'],
              i['IN_APOIO_MORADIA'],
              i['IN_APOIO_TRANSPORTE'],
              i['IN_ATIVIDADE_EXTRACURRICULAR'],
              i['IN_COMPLEMENTAR_ESTAGIO'],
              i['IN_COMPLEMENTAR_EXTENSAO'],
              i['IN_COMPLEMENTAR_MONITORIA'],
              i['IN_COMPLEMENTAR_PESQUISA'],
              i['IN_BOLSA_ESTAGIO'],
              i['IN_BOLSA_EXTENSAO'],
              i['IN_BOLSA_MONITORIA'],
              i['IN_BOLSA_PESQUISA'],
              i['TP_ESCOLA_CONCLUSAO_ENS_MEDIO'],
              i['IN_ALUNO_PARFOR'],
              i['TP_SEMESTRE_CONCLUSAO'],
              i['TP_SEMESTRE_REFERENCIA'],
              i['IN_MOBILIDADE_ACADEMICA'],
              i['TP_MOBILIDADE_ACADEMICA'],
              i['TP_MOBILIDADE_ACADEMICA_INTERN'],
              i['CO_IES_DESTINO'],
              i['CO_PAIS_DESTINO'],
              i['IN_MATRICULA'],
              i['IN_CONCLUINTE'],
              i['IN_INGRESSO_TOTAL'],
              i['IN_INGRESSO_VAGA_NOVA'],
              i['IN_INGRESSO_PROCESSO_SELETIVO'],
              i['NU_ANO_INGRESSO']
              ) for i in dr]

cur.executemany('''INSERT INTO ALUNOS (NU_ANO_CENSO,
 CO_IES,
 TP_CATEGORIA_ADMINISTRATIVA,
 TP_ORGANIZACAO_ACADEMICA,
 CO_CURSO,
 CO_CURSO_POLO,
 TP_TURNO,
 TP_GRAU_ACADEMICO,
 TP_MODALIDADE_ENSINO,
 TP_NIVEL_ACADEMICO,
 CO_OCDE_AREA_GERAL,
 CO_OCDE_AREA_ESPECIFICA,
 CO_OCDE_AREA_DETALHADA,
 CO_OCDE,
 CO_ALUNO,
 CO_ALUNO_CURSO,
 CO_ALUNO_CURSO_ORIGEM,
 TP_COR_RACA,
 TP_SEXO,
 NU_ANO_NASCIMENTO,
 NU_MES_NASCIMENTO,
 NU_DIA_NASCIMENTO,
 NU_IDADE,
 TP_NACIONALIDADE,
 CO_PAIS_ORIGEM,
 CO_UF_NASCIMENTO,
 CO_MUNICIPIO_NASCIMENTO,
 TP_DEFICIENCIA,
 IN_DEFICIENCIA_AUDITIVA,
 IN_DEFICIENCIA_FISICA,
 IN_DEFICIENCIA_INTELECTUAL,
 IN_DEFICIENCIA_MULTIPLA,
 IN_DEFICIENCIA_SURDEZ,
 IN_DEFICIENCIA_SURDOCEGUEIRA,
 IN_DEFICIENCIA_BAIXA_VISAO,
 IN_DEFICIENCIA_CEGUEIRA,
 IN_DEFICIENCIA_SUPERDOTACAO,
 IN_TGD_AUTISMO_INFANTIL,
 IN_TGD_SINDROME_ASPERGER,
 IN_TGD_SINDROME_RETT,
 IN_TGD_TRANSTOR_DESINTEGRATIVO,
 TP_SITUACAO,
 QT_CARGA_HORARIA_TOTAL,
 QT_CARGA_HORARIA_INTEG,
 DT_INGRESSO_CURSO,
 IN_INGRESSO_VESTIBULAR,
 IN_INGRESSO_ENEM,
 IN_INGRESSO_AVALIACAO_SERIADA,
 IN_INGRESSO_SELECAO_SIMPLIFICA,
 IN_INGRESSO_OUTRO_TIPO_SELECAO,
 IN_INGRESSO_VAGA_REMANESC,
 IN_INGRESSO_VAGA_PROG_ESPECIAL,
 IN_INGRESSO_TRANSF_EXOFFICIO,
 IN_INGRESSO_DECISAO_JUDICIAL,
 IN_INGRESSO_CONVENIO_PECG,
 IN_INGRESSO_EGRESSO,
 IN_INGRESSO_OUTRA_FORMA,
 IN_RESERVA_VAGAS,
 IN_RESERVA_ETNICO,
 IN_RESERVA_DEFICIENCIA,
 IN_RESERVA_ENSINO_PUBLICO,
 IN_RESERVA_RENDA_FAMILIAR,
 IN_RESERVA_OUTRA,
 IN_FINANCIAMENTO_ESTUDANTIL,
 IN_FIN_REEMB_FIES,
 IN_FIN_REEMB_ESTADUAL,
 IN_FIN_REEMB_MUNICIPAL,
 IN_FIN_REEMB_PROG_IES,
 IN_FIN_REEMB_ENT_EXTERNA,
 IN_FIN_REEMB_OUTRA,
 IN_FIN_NAOREEMB_PROUNI_INTEGR,
 IN_FIN_NAOREEMB_PROUNI_PARCIAL,
 IN_FIN_NAOREEMB_ESTADUAL,
 IN_FIN_NAOREEMB_MUNICIPAL,
 IN_FIN_NAOREEMB_PROG_IES,
 IN_FIN_NAOREEMB_ENT_EXTERNA,
 IN_FIN_NAOREEMB_OUTRA,
 IN_APOIO_SOCIAL,
 IN_APOIO_ALIMENTACAO,
 IN_APOIO_BOLSA_PERMANENCIA,
 IN_APOIO_BOLSA_TRABALHO,
 IN_APOIO_MATERIAL_DIDATICO,
 IN_APOIO_MORADIA,
 IN_APOIO_TRANSPORTE,
 IN_ATIVIDADE_EXTRACURRICULAR,
 IN_COMPLEMENTAR_ESTAGIO,
 IN_COMPLEMENTAR_EXTENSAO,
 IN_COMPLEMENTAR_MONITORIA,
 IN_COMPLEMENTAR_PESQUISA,
 IN_BOLSA_ESTAGIO,
 IN_BOLSA_EXTENSAO,
 IN_BOLSA_MONITORIA,
 IN_BOLSA_PESQUISA,
 TP_ESCOLA_CONCLUSAO_ENS_MEDIO,
 IN_ALUNO_PARFOR,
 TP_SEMESTRE_CONCLUSAO,
 TP_SEMESTRE_REFERENCIA,
 IN_MOBILIDADE_ACADEMICA,
 TP_MOBILIDADE_ACADEMICA,
 TP_MOBILIDADE_ACADEMICA_INTERN,
 CO_IES_DESTINO,
 CO_PAIS_DESTINO,
 IN_MATRICULA,
 IN_CONCLUINTE,
 IN_INGRESSO_TOTAL,
 IN_INGRESSO_VAGA_NOVA,
 IN_INGRESSO_PROCESSO_SELETIVO,
 NU_ANO_INGRESSO) VALUES (?, ?);''', to_db)
con.commit()
con.close()

FileNotFoundError: ignored

In [7]:
df_alunos = pd.read_csv('DM_ALUNO.zip', sep='|', nrows=1000000, low_memory=False)
df_cursos = pd.read_csv('DM_CURSO.zip', sep='|', low_memory=False, encoding='windows-1252')
df_docentes = pd.read_csv('DM_DOCENTE.zip', sep='|', low_memory=False)
df_ies = pd.read_csv('DM_IES.zip', sep='|', low_memory=False, encoding='windows-1252')
df_local_oferta = pd.read_csv('DM_LOCAL_OFERTA.zip', sep='|', low_memory=False, encoding='windows-1252')

FileNotFoundError: ignored

In [0]:
list(df_alunos.columns)

['NU_ANO_CENSO',
 'CO_IES',
 'TP_CATEGORIA_ADMINISTRATIVA',
 'TP_ORGANIZACAO_ACADEMICA',
 'CO_CURSO',
 'CO_CURSO_POLO',
 'TP_TURNO',
 'TP_GRAU_ACADEMICO',
 'TP_MODALIDADE_ENSINO',
 'TP_NIVEL_ACADEMICO',
 'CO_OCDE_AREA_GERAL',
 'CO_OCDE_AREA_ESPECIFICA',
 'CO_OCDE_AREA_DETALHADA',
 'CO_OCDE',
 'CO_ALUNO',
 'CO_ALUNO_CURSO',
 'CO_ALUNO_CURSO_ORIGEM',
 'TP_COR_RACA',
 'TP_SEXO',
 'NU_ANO_NASCIMENTO',
 'NU_MES_NASCIMENTO',
 'NU_DIA_NASCIMENTO',
 'NU_IDADE',
 'TP_NACIONALIDADE',
 'CO_PAIS_ORIGEM',
 'CO_UF_NASCIMENTO',
 'CO_MUNICIPIO_NASCIMENTO',
 'TP_DEFICIENCIA',
 'IN_DEFICIENCIA_AUDITIVA',
 'IN_DEFICIENCIA_FISICA',
 'IN_DEFICIENCIA_INTELECTUAL',
 'IN_DEFICIENCIA_MULTIPLA',
 'IN_DEFICIENCIA_SURDEZ',
 'IN_DEFICIENCIA_SURDOCEGUEIRA',
 'IN_DEFICIENCIA_BAIXA_VISAO',
 'IN_DEFICIENCIA_CEGUEIRA',
 'IN_DEFICIENCIA_SUPERDOTACAO',
 'IN_TGD_AUTISMO_INFANTIL',
 'IN_TGD_SINDROME_ASPERGER',
 'IN_TGD_SINDROME_RETT',
 'IN_TGD_TRANSTOR_DESINTEGRATIVO',
 'TP_SITUACAO',
 'QT_CARGA_HORARIA_TOTAL',
 'QT_CARGA_HORARIA_INTEG',
 'DT_INGRESSO_CURSO',
 'IN_INGRESSO_VESTIBULAR',
 'IN_INGRESSO_ENEM',
 'IN_INGRESSO_AVALIACAO_SERIADA',
 'IN_INGRESSO_SELECAO_SIMPLIFICA',
 'IN_INGRESSO_OUTRO_TIPO_SELECAO',
 'IN_INGRESSO_VAGA_REMANESC',
 'IN_INGRESSO_VAGA_PROG_ESPECIAL',
 'IN_INGRESSO_TRANSF_EXOFFICIO',
 'IN_INGRESSO_DECISAO_JUDICIAL',
 'IN_INGRESSO_CONVENIO_PECG',
 'IN_INGRESSO_EGRESSO',
 'IN_INGRESSO_OUTRA_FORMA',
 'IN_RESERVA_VAGAS',
 'IN_RESERVA_ETNICO',
 'IN_RESERVA_DEFICIENCIA',
 'IN_RESERVA_ENSINO_PUBLICO',
 'IN_RESERVA_RENDA_FAMILIAR',
 'IN_RESERVA_OUTRA',
 'IN_FINANCIAMENTO_ESTUDANTIL',
 'IN_FIN_REEMB_FIES',
 'IN_FIN_REEMB_ESTADUAL',
 'IN_FIN_REEMB_MUNICIPAL',
 'IN_FIN_REEMB_PROG_IES',
 'IN_FIN_REEMB_ENT_EXTERNA',
 'IN_FIN_REEMB_OUTRA',
 'IN_FIN_NAOREEMB_PROUNI_INTEGR',
 'IN_FIN_NAOREEMB_PROUNI_PARCIAL',
 'IN_FIN_NAOREEMB_ESTADUAL',
 'IN_FIN_NAOREEMB_MUNICIPAL',
 'IN_FIN_NAOREEMB_PROG_IES',
 'IN_FIN_NAOREEMB_ENT_EXTERNA',
 'IN_FIN_NAOREEMB_OUTRA',
 'IN_APOIO_SOCIAL',
 'IN_APOIO_ALIMENTACAO',
 'IN_APOIO_BOLSA_PERMANENCIA',
 'IN_APOIO_BOLSA_TRABALHO',
 'IN_APOIO_MATERIAL_DIDATICO',
 'IN_APOIO_MORADIA',
 'IN_APOIO_TRANSPORTE',
 'IN_ATIVIDADE_EXTRACURRICULAR',
 'IN_COMPLEMENTAR_ESTAGIO',
 'IN_COMPLEMENTAR_EXTENSAO',
 'IN_COMPLEMENTAR_MONITORIA',
 'IN_COMPLEMENTAR_PESQUISA',
 'IN_BOLSA_ESTAGIO',
 'IN_BOLSA_EXTENSAO',
 'IN_BOLSA_MONITORIA',
 'IN_BOLSA_PESQUISA',
 'TP_ESCOLA_CONCLUSAO_ENS_MEDIO',
 'IN_ALUNO_PARFOR',
 'TP_SEMESTRE_CONCLUSAO',
 'TP_SEMESTRE_REFERENCIA',
 'IN_MOBILIDADE_ACADEMICA',
 'TP_MOBILIDADE_ACADEMICA',
 'TP_MOBILIDADE_ACADEMICA_INTERN',
 'CO_IES_DESTINO',
 'CO_PAIS_DESTINO',
 'IN_MATRICULA',
 'IN_CONCLUINTE',
 'IN_INGRESSO_TOTAL',
 'IN_INGRESSO_VAGA_NOVA',
 'IN_INGRESSO_PROCESSO_SELETIVO',
 'NU_ANO_INGRESSO']

In [0]:
df_cursos.head()

   NU_ANO_CENSO  CO_IES  ...  QT_INGRESSO_PROCESSO_SELETIVO  QT_VAGA_TOTAL
0          2017     789  ...                            NaN             50
1          2017    4567  ...                            NaN             95
2          2017    2341  ...                            NaN            240
3          2017     670  ...                            NaN            191
4          2017     403  ...                            NaN            840

[5 rows x 114 columns]

In [0]:
df_alunos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Columns: 108 entries, NU_ANO_CENSO to NU_ANO_INGRESSO
dtypes: float64(65), int64(41), object(2)
memory usage: 824.0+ MB

In [0]:
df_docentes.head()

   NU_ANO_CENSO  CO_IES  ...  IN_VISITANTE  TP_VISITANTE_IFES_VINCULO
0          2017   18812  ...           0.0                        NaN
1          2017   18812  ...           0.0                        NaN
2          2017    1683  ...           0.0                        NaN
3          2017    1683  ...           0.0                        NaN
4          2017    1683  ...           0.0                        NaN

[5 rows x 41 columns]

In [0]:
df_ies.head()

   NU_ANO_CENSO  CO_IES  ... VL_DESPESA_PESQUISA VL_DESPESA_OUTRA
0          2017       1  ...          5807924.06     1.937327e+08
1          2017       2  ...          5772538.37     4.263122e+08
2          2017       3  ...          3033336.32     1.625782e+08
3          2017       4  ...          1490990.75     1.348790e+08
4          2017       6  ...           748715.26     1.171686e+08

[5 rows x 47 columns]

In [0]:
df_local_oferta.head()

   NU_ANO_CENSO  ...  IN_SALA_ATENDIMENTO_TUTOR
0          2017  ...                        1.0
1          2017  ...                        1.0
2          2017  ...                        1.0
3          2017  ...                        1.0
4          2017  ...                        1.0

[5 rows x 50 columns]

In [0]:
df_ies.describe().T

                                 count  ...           max
NU_ANO_CENSO                    2448.0  ...  2.017000e+03
CO_IES                          2448.0  ...  2.293900e+04
CO_MANTENEDORA                  2448.0  ...  1.684300e+04
TP_CATEGORIA_ADMINISTRATIVA     2448.0  ...  7.000000e+00
TP_ORGANIZACAO_ACADEMICA        2448.0  ...  5.000000e+00
CO_REGIAO                       2448.0  ...  5.000000e+00
CO_UF                           2448.0  ...  5.300000e+01
CO_MUNICIPIO                    2448.0  ...  5.300108e+06
IN_CAPITAL                      2448.0  ...  1.000000e+00
QT_TEC_TOTAL                    2448.0  ...  1.494500e+04
QT_TEC_FUNDAMENTAL_INCOMP_FEM   2448.0  ...  5.190000e+02
QT_TEC_FUNDAMENTAL_INCOMP_MASC  2448.0  ...  5.600000e+02
QT_TEC_FUNDAMENTAL_COMP_FEM     2448.0  ...  2.930000e+02
QT_TEC_FUNDAMENTAL_COMP_MASC    2448.0  ...  5.330000e+02
QT_TEC_MEDIO_FEM                2448.0  ...  2.569000e+03
QT_TEC_MEDIO_MASC               2448.0  ...  3.569000e+03
QT_TEC_SUPERIOR_FEM             2448.0  ...  2.207000e+03
QT_TEC_SUPERIOR_MASC            2448.0  ...  1.885000e+03
QT_TEC_ESPECIALIZACAO_FEM       2448.0  ...  1.393000e+03
QT_TEC_ESPECIALIZACAO_MASC      2448.0  ...  7.280000e+02
QT_TEC_MESTRADO_FEM             2448.0  ...  7.300000e+02
QT_TEC_MESTRADO_MASC            2448.0  ...  4.080000e+02
QT_TEC_DOUTORADO_FEM            2448.0  ...  4.060000e+02
QT_TEC_DOUTORADO_MASC           2448.0  ...  2.610000e+02
IN_ACESSO_PORTAL_CAPES          2448.0  ...  1.000000e+00
IN_ACESSO_OUTRAS_BASES          2448.0  ...  1.000000e+00
IN_REPOSITORIO_INSTITUCIONAL    2448.0  ...  1.000000e+00
IN_BUSCA_INTEGRADA              2448.0  ...  1.000000e+00
IN_SERVICO_INTERNET             2448.0  ...  1.000000e+00
IN_PARTICIPA_REDE_SOCIAL        2448.0  ...  1.000000e+00
IN_CATALOGO_ONLINE              2448.0  ...  1.000000e+00
QT_PERIODICO_ELETRONICO         2448.0  ...  2.008354e+07
QT_LIVRO_ELETRONICO             2448.0  ...  1.000000e+07
TP_REFERENTE                    2448.0  ...  2.000000e+00
VL_RECEITA_PROPRIA              2448.0  ...  6.248050e+09
VL_RECEITA_TRANSFERENCIA        2448.0  ...  7.078090e+09
VL_RECEITA_OUTRA                2448.0  ...  9.510644e+08
VL_DESPESA_PESSOAL_DOCENTE      2448.0  ...  7.600039e+09
VL_DESPESA_PESSOAL_TECNICO      2448.0  ...  9.387072e+09
VL_DESPESA_PESSOAL_ENCARGO      2448.0  ...  9.173800e+09
VL_DESPESA_CUSTEIO              2448.0  ...  8.548603e+09
VL_DESPESA_INVESTIMENTO         2448.0  ...  1.439885e+09
VL_DESPESA_PESQUISA             2448.0  ...  1.712282e+08
VL_DESPESA_OUTRA                2448.0  ...  1.948600e+09

[44 rows x 8 columns]

In [0]:
df_ies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2448 entries, 0 to 2447
Data columns (total 47 columns):
NU_ANO_CENSO                      2448 non-null int64
CO_IES                            2448 non-null int64
NO_IES                            2448 non-null object
SG_IES                            2081 non-null object
CO_MANTENEDORA                    2448 non-null int64
NO_MANTENEDORA                    2448 non-null object
TP_CATEGORIA_ADMINISTRATIVA       2448 non-null int64
TP_ORGANIZACAO_ACADEMICA          2448 non-null int64
CO_REGIAO                         2448 non-null int64
CO_UF                             2448 non-null int64
CO_MUNICIPIO                      2448 non-null int64
IN_CAPITAL                        2448 non-null int64
QT_TEC_TOTAL                      2448 non-null int64
QT_TEC_FUNDAMENTAL_INCOMP_FEM     2448 non-null int64
QT_TEC_FUNDAMENTAL_INCOMP_MASC    2448 non-null int64
QT_TEC_FUNDAMENTAL_COMP_FEM       2448 non-null int64
QT_TEC_FUNDAMENTAL_COMP_MASC      2448 non-null int64
QT_TEC_MEDIO_FEM                  2448 non-null int64
QT_TEC_MEDIO_MASC                 2448 non-null int64
QT_TEC_SUPERIOR_FEM               2448 non-null int64
QT_TEC_SUPERIOR_MASC              2448 non-null int64
QT_TEC_ESPECIALIZACAO_FEM         2448 non-null int64
QT_TEC_ESPECIALIZACAO_MASC        2448 non-null int64
QT_TEC_MESTRADO_FEM               2448 non-null int64
QT_TEC_MESTRADO_MASC              2448 non-null int64
QT_TEC_DOUTORADO_FEM              2448 non-null int64
QT_TEC_DOUTORADO_MASC             2448 non-null int64
IN_ACESSO_PORTAL_CAPES            2448 non-null int64
IN_ACESSO_OUTRAS_BASES            2448 non-null int64
IN_REPOSITORIO_INSTITUCIONAL      2448 non-null int64
IN_BUSCA_INTEGRADA                2448 non-null int64
IN_SERVICO_INTERNET               2448 non-null int64
IN_PARTICIPA_REDE_SOCIAL          2448 non-null int64
IN_CATALOGO_ONLINE                2448 non-null int64
QT_PERIODICO_ELETRONICO           2448 non-null int64
QT_LIVRO_ELETRONICO               2448 non-null int64
TP_REFERENTE                      2448 non-null int64
VL_RECEITA_PROPRIA                2448 non-null float64
VL_RECEITA_TRANSFERENCIA          2448 non-null float64
VL_RECEITA_OUTRA                  2448 non-null float64
VL_DESPESA_PESSOAL_DOCENTE        2448 non-null float64
VL_DESPESA_PESSOAL_TECNICO        2448 non-null float64
VL_DESPESA_PESSOAL_ENCARGO        2448 non-null float64
VL_DESPESA_CUSTEIO                2448 non-null float64
VL_DESPESA_INVESTIMENTO           2448 non-null float64
VL_DESPESA_PESQUISA               2448 non-null float64
VL_DESPESA_OUTRA                  2448 non-null float64
dtypes: float64(10), int64(34), object(3)
memory usage: 899.0+ KB

In [0]:
#db = sqlite3.connect('censo_educacao_superior_2017.db')

In [0]:
sqlDataTypes={}

for c in df_alunos.columns:
    if df_alunos[c].dtype.kind == 'i':
        sqlDataTypes[c]='INTEGER'
    elif df_alunos[c].dtype.kind == 'f':
        sqlDataTypes[c]='REAL'
    else:
        sqlDataTypes[c]='TEXT'

In [0]:
#df_alunos.to_sql('alunos', index=True, if_exists='replace', dtype=sqlDataTypes, con=db)

In [0]:
#db.commit()
#db.close()

1) Tabelas com número de universidades públicas e privadas por estado e número de alunos por universidade

In [0]:
df_ies.head()

   NU_ANO_CENSO  CO_IES  ... VL_DESPESA_PESQUISA VL_DESPESA_OUTRA
0          2017       1  ...          5807924.06     1.937327e+08
1          2017       2  ...          5772538.37     4.263122e+08
2          2017       3  ...          3033336.32     1.625782e+08
3          2017       4  ...          1490990.75     1.348790e+08
4          2017       6  ...           748715.26     1.171686e+08

[5 rows x 47 columns]

In [0]:
df_ies['CO_UF'].value_counts()

35    611
31    296
41    189
33    136
29    133
43    123
26    106
42     93
52     89
32     78
23     72
53     64
51     59
15     54
21     45
22     44
25     42
11     34
27     29
50     28
24     28
17     24
13     20
28     18
16     15
12     11
14      7
Name: CO_UF, dtype: int64

In [0]:
df_ies['TIPO'] = df_ies.TP_CATEGORIA_ADMINISTRATIVA.replace({1:1, 2:1, 3:1, 4:2, 5:2, 6:2, 7:3})

In [0]:
df_ies.TIPO.value_counts()

2    2152
1     286
3      10
Name: TIPO, dtype: int64

In [0]:
df_ies.groupby(['TIPO', 'CO_UF']).sum()

            NU_ANO_CENSO   CO_IES  ...  VL_DESPESA_PESQUISA  VL_DESPESA_OUTRA
TIPO CO_UF                         ...
1    11             4034     5484  ...         1.609089e+06      8.976024e+07
     12             4034    16056  ...         4.500000e+05      0.000000e+00
     13             6051     4988  ...         4.080713e+06      1.348790e+08
     14             6051     9050  ...         7.772749e+05      1.308274e+07
     15            12102    36509  ...         2.364875e+07      3.805732e+07
     16             6051    22053  ...         1.547563e+06      6.116637e+06
     17            10085    11860  ...         1.827116e+06      2.252859e+05
     21             6051     1716  ...         1.154344e+07      2.258041e+08
     22             6051     2581  ...         9.227742e+06      3.641160e+07
     23            14119    37516  ...         1.330367e+07      8.211555e+07
     24            10085     5672  ...         2.387821e+07      5.818374e+08
     25             8068     4859  ...         1.769215e+07      2.230021e+08
     26            42357    60783  ...         4.683655e+06      8.986262e+07
     27             8068     9011  ...         9.804447e+06      1.449487e+09
     28             4034     3186  ...         5.604856e+06      1.650138e+08
     29            20170    58925  ...         3.783618e+07      7.447586e+07
     31            46391    35582  ...         1.304987e+08      1.253495e+09
     32            10085     4528  ...         3.233732e+07      3.943993e+07
     33            54459   130167  ...         3.051909e+07      1.756006e+09
     35           197666   904859  ...         2.139319e+08      4.634530e+08
     41            26221    68106  ...         1.306980e+08      6.935653e+08
     42            16136    34485  ...         1.393924e+07      5.367457e+08
     43            20170    17461  ...         6.360671e+07      5.195793e+08
     50             8068    21746  ...         4.279023e+06      1.523570e+08
     51             6051     3884  ...         5.910849e+06      1.937327e+08
     52            16136    13683  ...         3.240310e+07      1.483222e+09
     53             8068    33670  ...         7.131736e+06      4.263130e+08
2    11            64544   147404  ...         1.812184e+07      5.075510e+08
     12            18153    24630  ...         1.800000e+04      5.334723e+07
     13            34289    46166  ...         9.632718e+06      4.896772e+08
     14             8068    11891  ...         2.846640e+05      1.371390e+07
     15            96816   423678  ...         1.394562e+07      7.215143e+08
     16            24204    40009  ...         1.731405e+06      5.879458e+08
     17            38323   123934  ...         9.181511e+06      3.502054e+08
     21            84714   333474  ...         4.871244e+06      1.078692e+09
     22            82697   213367  ...         2.761852e+06      6.776144e+07
     23           131105   540244  ...         4.365055e+06      1.725506e+09
     24            46391   125177  ...         3.035344e+05      2.305530e+09
     25            76646   245323  ...         2.404914e+07      1.019612e+09
     26           157326   469995  ...         5.964798e+06      1.979505e+09
     27            50425   156200  ...         6.367337e+06      5.147574e+08
     28            32272    96158  ...         5.965902e+05      2.049135e+08
     29           248091   687651  ...         1.684950e+08      3.229266e+09
     31           550641  1442352  ...         5.287377e+07      3.783152e+09
     32           147241   304543  ...         1.000481e+07      2.221490e+09
     33           219853   338219  ...         6.515245e+07      1.832527e+09
     35          1028670  2084951  ...         5.023057e+08      2.009728e+10
     41           354992   848531  ...         4.217762e+07      4.529052e+09
     42           171445   425755  ...         6.734583e+07      1.928850e+09
     43           227921   604711  ...         1.861608e+08      2.606432e+09
     50            48408    67936  ...         2.356090e+07      1.133082e+09
     51           112952   284231  ...         4.599275e+06      1.301978e+09
     52           163377   417960  ...         5.187836e+07      1.495031e+09
     53           121020   321587  ...         5.986411e+07      1.325004e+09
3    26            14119    32662  ...         1.578484e+04      1.069209e+06
     35             6051     1569  ...         5.165532e+05      3.077099e+06

[56 rows x 43 columns]